# Generated by Django 3.1.4 on 2023-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20230323_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=True),
        ),
    ]
