# Generated by Django 4.1.7 on 2023-03-27 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20230326_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='number',
            field=models.CharField(default='', max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
