# Generated by Django 4.1.7 on 2023-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_date_added_lead_email_lead_number_lead_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='number',
            field=models.CharField(max_length=19, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='review',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
