# Generated by Django 4.1.7 on 2023-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_date_added_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обращения'),
        ),
    ]
